# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: actionTest

on: [ workflow_dispatch, push, pull_request ]
env:
  JAVA_VERSION: 11.0.3
  SERVER_ID: snapshots
  PYTHON_VERSION: '3.x'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ] #ubuntu-latest,, macos-latest

    steps:
      # https://github.com/msys2/setup-msys2
      #      - uses: msys2/setup-msys2@v2
      #        if: matrix.os == 'windows-latest'
      #        name: MSYS
      #        with:
      #          path-type: inherit
      #          msystem: MINGW64
      #          install: >-
      #            mingw-w64-x86_64-toolchain
      #            mingw-w64-x86_64-cmake
      #            mingw-w64-x86_64-ninja

#      - name: Set up Java
#        uses: actions/setup-java@v1.4.3
#        with:
#          java-version: ${{ env.JAVA_VERSION }}


      - uses: actions/checkout@v2

#      - name: Maven Build
#        run: mvn -D"org.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn" -B package --file pom.xml -DskipTests

      - name: Put MSYS2_MinGW64 on PATH
         # there is not yet an environment variable for this path from msys2/setup-msys2
        run: echo "C:\msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: cmake version        #        if: matrix.os == 'windows-latest'
        #        shell: msys2 {0}
        run: cmake --version


      - name: gcc        #        if: matrix.os == 'windows-latest'
        #        shell: msys2 {0}
        run: gcc --version

      - name: cmake        #        if: matrix.os == 'windows-latest'
        #        shell: msys2 {0}
        run: cmake -G"MSYS Makefiles" -Bbuild -S cpp


      - name: Compile        #        if: matrix.os == 'windows-latest'
        #        shell: msys2 {0}
        run: make -Cbuild install
