# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: actionTest

on: [ workflow_dispatch, push, pull_request ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ] #ubuntu-latest,, macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Put MSYS2_MinGW64 on PATH
         # there is not yet an environment variable for this path from msys2/setup-msys2
        run: echo "C:\msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: cmake version 
        run: cmake --version

      - name: gcc 
        run: gcc --version

      - name: cmake       
        run: cmake -G"MSYS Makefiles" -DCMAKE_INSTALL_PREFIX=target -Bbuild -S cpp

      - name: Compile  
        run: make -Cbuild -j9  install

      - name: output dependencies
        run: ldd target/bin/sim.exe

      - name: check sha1      
        run: target/bin/sim.exe -sha1

      - name: run simulation       
        run: target/bin/sim.exe

      - name: upload executable
        uses: actions/upload-artifact@v2
        if: ${{ always()}}
        with:
          name: output
          path: |
            **/*.fmu
            target/**/*
          retention-days: 1

      - name: upload unzipped
        uses: actions/upload-artifact@v2
        if: ${{ always()}}
        with:
          name: output_unzipped
          path: |
            C:/Users/RUNNER~1/AppData/Local/Temp/**/binaries/*
          retention-days: 1

      - name: run simulation   
        if: ${{ always()}}    
        run: cat C:\Users\RUNNER~1\AppData\Local\Temp\_8c4e810f-3df3-4a00-8276-176fa3c9f000_\modelDescription.xml
